title: "Tide Supreme"
description: "Stay updated with the latest insights on the next frontier of cybersecurity, privacy, zero-knowledge cryptography, and data sovereignty from Tide Foundation."
theme: minima

# Optional but nice:
author: tidesupreme
