title: "Tide Supreme"
description: "Stay updated with the latest insights on the next frontier of cybersecurity, privacy, zero-knowledge cryptography, and data sovereignty from Tide Foundation."
theme: minima

minima:
  show_excerpts: true
  social_links:
    - title: Tide repository
      icon: github
      url: "https://github.com/TideSupreme"
    - title: Tide at X
      icon: x-twitter
      url: "https://x.com/tide-foundation"

author:
  name: Tide Team
  email: "info@tide.org"
